# Generated by Django 5.1.2 on 2024-10-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('daraja', models.CharField(max_length=50)),
                ('ustoz', models.CharField(max_length=255)),
                ('narx', models.PositiveSmallIntegerField()),
                ('chegirma', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('sana', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=255)),
                ('sana', models.DateField(auto_now=True)),
                ('baho', models.CharField(max_length=400)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohirdev.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohirdev.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohirdev.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohirdev.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohirdev.kurs')),
                ('progil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohirdev.profil')),
            ],
        ),
    ]
